### ISSUE TITLE
macOS Sierra: could not launch process: could not get thread count

### ISSUE THREAD

**Issue by integrii** [derekparker/delve#577]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
```

2. What version of Go are you using? (`go version`)?
`go version go1.6.2 darwin/amd64
`
3. What operating system and processor architecture are you using?
`macOS 10.12 Beta (16A201w)`

4. What did you do?
`dlv debug *.go`

5. What did you expect to see?
dlv prompt

6. What did you see instead?
`could not launch process: could not get thread count`

I installed with brew, then threw that away and built/signed my own dlv.  Same issue!  macOS sierra broken?

**Comment by integrii** [comment]
This is fixed in MacOS Sierra Beta 2!

**Comment by antonyr** [comment]
This issue is not solved yet in MacOS Sierra final build (10.12.1)

**Comment by aarzilli** [comment]
See #645

**Comment by Greymarch** [comment]
I also started getting this bug today.

**Comment by kolov** [comment]
I just decided to give Go a try but it looks like debugging will not be available for a while, is that correct? That's the error I get in IntelliJ running on Mac OS 10.12.1.

**Comment by lloiacono** [comment]
Same problem with Goglang and Mac OS 10.12.4
